#ifndef FLOWCONTROLSTATES_H
#define FLOWCONTROLSTATES_H

enum class FlowControlState
{
    // --- System States ---
    IDLE,
    RUNNING,
    JOB_FAILED,

    // --- Vision Calibration Sequence ---
    BOARD_DETECT_SAFE_START_STATE,
    CALIBRATION_HOME,
    CALIBRATION_HOMING,
    MOVE_Z_SAFE_CALIBRATION,
    MOVE_TO_FIDUCIAL_1,
    DETECT_FIDUCIAL_1,
    MOVE_TO_FIDUCIAL_2,
    DETECT_FIDUCIAL_2,
    MOVE_TO_FIDUCIAL_3,
    DETECT_FIDUCIAL_3,
    MOVE_TO_FIDUCIAL_4,
    DETECT_FIDUCIAL_4,
    CALCULATE_BOARD_TRANSFORM,

    // --- Pick and Place Job Sequence ---
    FEEDER_SAFE_START_STATE,
    GET_NEXT_COMPONENT,
    WAIT_FOR_USER_CUTTAPE_RELOAD,
    ADVANCE_FEEDER,

    PNP_HOME,
    PNP_HOMING,

    PICKUP_SAFE_START_STATE,
    MOVE_Z_SAFE_PICK,
    MOVE_XY_TO_FEEDER,
    LOWER_Z_TO_PICK,
    ENABLE_VACUUM,
    DWELL_FOR_VACUUM,
    RAISE_Z_FROM_PICK,

    PLACE_DETECT_SAFE_START_STATE,
    MOVE_XY_TO_UPWARD_CAMERA,
    DETECT_COMPONENT_POSE,
    MOVING_TO_CORRECTED_POSITION,
    ROTATE_HEAD_A_AXIS,
    LOWER_Z_TO_DROP,
    DISABLE_VACUUM,
    DWELL_FOR_RELEASE,
    RAISE_Z_FROM_DROP,

    // --- Error Handling & Interrupts ---
    PAUSE,
    AWAIT_OPERATOR_RESUME,
    MACHINE_IS_STUPID,

    COUNT
};

#endif /* FLOWCONTROLSTATES_H */
